name: Increment Build Number, Deploy and Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main
      - '*' # This wildcard matches all branches except 'main' due to the job-level 'if' conditions

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Increment build number
        run: |
          # Read the current build number
          build_number=$(cat build-number.txt)

          # Increment the build number
          echo $(($build_number + 1)) > build-number.txt

          # Commit and push the change
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add build-number.txt
          git commit -m "Increment build number"
          git push

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run:
          vercel pull --yes --environment=production --token=${{
          secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  build-preview:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel Preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/[^a-zA-Z0-9]/-/g')
          echo "Deploying to preview environment for branch: $BRANCH_NAME"
          vercel --token=$VERCEL_TOKEN --confirm --name "crypto-stdev-cra-$BRANCH_NAME" --alias "$BRANCH_NAME.crypto-stdev-cra.vercel.app"
